Added a scenario for C3 integration with multi ksqldb and connect
confluentinc/operator-earlyaccess pull request #22
Opened 2020-12-17 23:51 UTC by arodoni

2020-12-18 23:45 UTC, rohit2b requested changes
Added some changes, apart from that looks great!

2020-12-21 17:54 UTC, arodoni commented on controlcenter-multi-ksql-connect/README.rst
> +  export TUTORIAL_HOME=<Tutorial directory>/secure-authn-encrypt-deploy
Fixed

2020-12-21 17:59 UTC, arodoni commented on controlcenter-multi-ksql-connect/README.rst
> +     helm upgrade --install operator confluentinc/confluent-operator --set image.registry=confluent-docker-internal-early-access-operator-2.jfrog.io
Done

2020-12-21 18:00 UTC, arodoni commented on controlcenter-multi-ksql-connect/README.rst
> +       -subj "/C=US/ST=CA/L=MountainView/O=Confluent/OU=Opeator/CN=TestCA"
Fixed

2020-12-21 19:58 UTC, rohit2b approved these changes
LGTM!

2020-12-23 17:48 UTC, merged