Rohit2b/helm commands
confluentinc/operator-earlyaccess pull request #30
Opened 2021-02-12 20:37 UTC by rohit2b

Document helper Helm commands

2021-02-12 23:40 UTC, arodoni requested changes

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +::
```suggestion
::

```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +::
```suggestion
::

```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +::
```suggestion
::

```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +::
```suggestion
::

```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +::
```suggestion
::

```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +::
```suggestion
::

```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +::
```suggestion
::

```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +View all helm charts in your Helm repository:
```suggestion
View all Helm charts in your Helm repository:
```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +Remove a specific helm chart from your Helm repository
```suggestion
Remove a specific Helm chart from your Helm repository
```

2021-02-12 23:40 UTC, arodoni commented on use-helm/README.rst
> +helm install <release> <chart>
```suggestion
::

   helm install <release> <chart>
   
```

2021-02-13 16:02 UTC, rohit2b commented
Thanks @arodoni ! Incorporated your review suggestions. Could you re-review?

2021-02-13 17:14 UTC, arodoni approved these changes
LGTM!

2021-02-13 17:48 UTC, merged